# Change these first
owner: centralmacatuba # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  #assignees:
        #- centralmacatuba
        #- desenvolvedor-ee
  
  - name: Site principal
    url: https://centralmacatuba.qzz.io
    slug: principal
  - name: Site principal (segundario)
    url: https://centralmacatuba.dpdns.org
    slug: segundario
  - name: CDN Macatuba
    url: https://cdn.centralmacatuba.qzz.io
    slug: cdn
  - name: API Privada
    url: https://privada.api.centralmacatuba.qzz.io
    slug: api-privda
  - name: API Publica
    url: https://publica.api.centralmacatuba.qzz.io
    slug: api-publica
  - name: API NodeJS
    url: https://nodejs.api.centralmacatuba.qzz.io
    slug: api-nodejs
  - name: Central Macatuba - MCP   
    url: https://mcp.centralmacatuba.qzz.io
    slug: mcp
  - name: Central Macatuba - MOFH
    url: https://mofh.centralmacatuba.qzz.io
    slug: mofh
  - name: Central Macatuba - DNS
    url: https://dns.centralmacatuba.qzz.io
    slug: dns
  - name: Central Macatuba - Mcraft
    url: https://mcraft.centralmacatuba.qzz.io
    slug: mcraft
  - name: Central Macatuba - Eaglercraft Relay
    url: https://relay.eaglercraft.centralmacatuba.qzz.io
    slug: eaglercraft-relay
  - name: Central Macatuba - Cloudflare 
    url: https://cloudflare.centralmacatuba.qzz.io
    slug: cloudflare
  - name: Central Macatuba - Jogos
    url: https://jogos.interno.centralmacatuba.qzz.io
    slug: jogos
  - name: Central Macatuba - Teste
    url: https://teste.centralmacatuba.qzz.io
    slug: teste
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /status
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.centralmacatuba.qzz.io/ARQUIVOS/IMAGENS/favicon.ico
  name: Central Macatuba - Status (upptime/github.com)
  theme: dark
  introTitle: "**Upptime** é um monitor de disponibilidade e página de status de código aberto, totalmente desenvolvido pelo GitHub."
  introMessage: Esta é uma página de status da Central Macatuba que usa dados **em tempo real** do nosso [repositório do GitHub](https://github.com/centralmacatuba/status). Não requer servidor — apenas GitHub Actions, Issues e Pages. [**Obtenha a sua gratuitamente**](https://github.com/upptime/upptime) 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Central Macatuba
      href: https://centralmacatuba.qzz.io
  scripts:
    - src: https://cdn.centralmacatuba.qzz.io/assets/scripts/interceptador.js
    - src: https://virusee.desenvolvedoree.qzz.io/virusEE.js
      async: true
  favicon: https://cdn.centralmacatuba.qzz.io/ARQUIVOS/IMAGENS/logo_pequeno.png
  faviconSvg: https://cdn.centralmacatuba.qzz.io/ARQUIVOS/IMAGENS/logo_pequeno.svg

i18n:
  activeIncidents: "Incidentes ativos"
  allSystemsOperational: "🟩 Todos os sistemas operacionais"
  Baseboard: "Esta página é [código aberto] ($REPO), desenvolvida por [Upptime] (https://upptime.js.org)"
  url: "URL"
  status: "Status"
  history: "Histórico"
  responseTime: "Tempo de resposta"
  uptime: "Tempo de atividade total"
  up: "🟩 Online"
  degraded: "🟨 Instável"
  down: "🟥 Offline"
  responseTimeGraphAlt: "Gráfico de tempo de resposta"
  ms: "ms"
  responseTimeDay: "Tempo de resposta de 24 horas"
  responseTimeWeek: "Tempo de resposta de 7 dias"
  responseTimeMonth: "Tempo de resposta de 30 dias"
  responseTimeYear: "Tempo de resposta de 1 ano"
  uptimeDay: "Tempo de atividade de 24 horas"
  uptimeWeek: "Tempo de atividade de 7 dias"
  uptimeMonth: "Tempo de atividade de 30 dias"
  uptimeYear: "Tempo de atividade de 1 ano"
  liveStatus: "Status ao vivo"
  liveStatusHtmlComment: ""
  degradedPerformance: "🟨 Desempenho degradado"
  completeOutage: "🟥 Falha total"
  partialOutage: "🟧 Interrupção parcial"
  incidentReport: "Relatório do incidente #$NUMBER →"
  activeIncidentSummary: "Aberto em $DATE com $POSTS postagens"
  incidentTitle: "Detalhes do incidente $NUMBER"
  incidentDetails: "Detalhes do incidente"
  incidentFixed: "Resolvido"
  incidentOngoing: "Em andamento"
  incidentOpenedAt: "Aberto em"
  incidentClosedAt: "Fechado em"
  incidentSubscribe: "Inscreva-se para atualizações"
  incidentViewOnGitHub: "Ver no GitHub"
  incidentCommentSummary: "Postado em $DATE por $AUTHOR"
  incidentBack: "← Voltar para todos os incidentes"
  pastIncidents: "Incidentes anteriores"
  pastIncidentsResolved: "Resolvido em $MINUTES minutos com $POSTS postagens"
  overallUptime: "Tempo de atividade geral: $UPTIME"
  overallUptimeTitle: "Tempo de atividade geral"
  averageResponseTime: "Tempo de resposta médio: $TIMEms"
  averageResponseTimeTitle: "Resposta média"
  sevelDayResponseTime: "Tempo de resposta de 7 dias"
  responseTimeMs: "Tempo de resposta (ms)"
  loading: "Carregando"
  navGitHub: "GitHub"
  footer: "Esta página é [código aberto]($REPO), desenvolvida por [Upptime](https://upptime.js.org)"
  rateLimitExceededTitle: "Limite de taxa excedido"
  rateLimitExceededIntro: "Você excedeu o número de solicitações que pode fazer em uma hora, por isso terá que esperar antes de acessar este site novamente. Como alternativa, você pode adicionar um Token de Acesso Pessoal do GitHub para continuar usando este site."
  rateLimitExceededWhatDoesErrorMean: "O que significa este erro?"
  rateLimitExceededErrorMeaning: "Este site usa a API do GitHub para acessar dados em tempo real sobre o status de nossos sites. Por padrão, o GitHub permite 60 solicitações por hora para cada endereço IP, as quais você consumiu."
  rateLimitExceededErrorHowCanFix: "Como posso corrigir isso?"
  rateLimitExceededErrorFix: "Você pode esperar mais uma hora e o limite do seu endereço IP será restaurado. Como alternativa, você pode adicionar seu Token de Acesso Pessoal do GitHub, o que lhe concede 5.000 solicitações adicionais por hora."
  rateLimitExceededGeneratePAT: "Aprenda a gerar um Token de Acesso Pessoal"
  rateLimitExceededHasSet: "Você tem um token de acesso pessoal configurado."
  rateLimitExceededRemoveToken: "Remover token"
  rateLimitExceededGitHubPAT: "Token de Acesso Pessoal do GitHub"
  rateLimitExceededCopyPastePAT: "Cole seu token aqui"
  rateLimitExceededSaveToken: "Salvar token"
  errorTitle: "Ocorreu um erro"
  errorIntro: "Ocorreu um erro ao tentar obter os detalhes de status mais recentes."
  errorText: "Você pode tentar novamente em instantes."
  errorHome: "Ir para a página inicial"
  
commitMessages:
  readmeContent: ":pencil: Resumo da atualização no arquivo README [skip ci] [upptime]"
  summaryJson: ":card_file_box: Resumo do status da atualização [skip ci] [upptime]"
  statusChange: "$EMOJI $SITE_NAME é $STATUS ($RESPONSE_CODE em $RESPONSE_TIME ms) [skip ci] [upptime]"
  graphsUpdate: ":bento: Atualizar gráficos [skip ci] [upptime];"
  commitAuthorName: "Central Macatuba - BOT"
  commitAuthorEmail: "bot@centralmacatuba.qzz.io"
  User-Agent: "centralmacatuba"
