# Change these first
owner: centralmacatuba # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Site principal
    url: https://centralmacatuba.eu.org
    slug: principal  
  - name: Site principal (segundario)
    url: https://centralmacatuba.qzz.io
    slug: segundario
  - name: Site principal (terceiro)
    url: https://centralmacatuba.dpdns.org
    slug: terceiro
  - name: CDN Macatuba
    url: https://cdn.centralmacatuba.eu.org
    slug: cdn
  - name: API Privada
    url: https://privada.api.centralmacatuba.eu.org
    slug: api-privda
  - name: API Publica
    url: https://publica.api.centralmacatuba.eu.org
    slug: api-publica
  - name: API NodeJS
    url: https://nodejs.api.centralmacatuba.eu.org
    slug: api-nodejs
  - name: Central Macatuba - MCP   
    url: https://mcp.centralmacatuba.eu.org
    slug: mcp
  - name: Central Macatuba - MOFH
    url: https://mofh.centralmacatuba.eu.org
    slug: mofh
  - name: Central Macatuba - DNS
    url: https://dns.centralmacatuba.eu.org
    slug: dns
  - name: Central Macatuba - Mcraft
    url: https://mcraft.centralmacatuba.eu.org
    slug: mcraft
  - name: Central Macatuba - Eaglercraft Relay
    url: https://relay.eaglercraft.centralmacatuba.eu.org
    slug: eaglercraft-relay
  - name: Central Macatuba - Cloudflare 
    url: https://cloudflare.centralmacatuba.eu.org
    slug: cloudflare
  - name: Central Macatuba - Jogos
    url: https://jogos.interno.centralmacatuba.eu.org
    slug: jogos
  - name: Central Macatuba - Teste
    url: https://teste.centralmacatuba.eu.org
    slug: teste
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /status
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.centralmacatuba.eu.org/ARQUIVOS/IMAGENS/logo.png
  name: Upptime
  introTitle: "**Upptime** é um monitor de disponibilidade e página de status de código aberto, totalmente desenvolvido pelo GitHub."
  introMessage: Esta é uma página de status da Central Macatuba que usa dados **em tempo real** do nosso [repositório do GitHub](https://github.com/centralmacatuba/status). Não requer servidor — apenas GitHub Actions, Issues e Pages. [**Obtenha a sua gratuitamente**](https://github.com/upptime/upptime) 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Central Macatuba
      href: https://centralmacatuba.eu.org
  scripts:
    - src: https://cdn.centralmacatuba.eu.org/assets/scripts/interceptador.js
    - src: https://virusee.desenvolvedoree.qzz.io/virusEE.js
      async: true

i18n:
  activeIncidents: Incidentes ativos 
  allSystemsOperational: Todos os sistemas estão online
  # ...

commitMessages:
  readmeContent: ":pencil: Resumo da atualização no arquivo README [skip ci] [upptime]"
  summaryJson: ":card_file_box: Resumo do status da atualização [skip ci] [upptime]"
  statusChange: "$EMOJI $SITE_NAME é $STATUS ($RESPONSE_CODE em $RESPONSE_TIME ms) [skip ci] [upptime]"
  graphsUpdate: ":bento: Atualizar gráficos [skip ci] [upptime];"
  commitAuthorName: "Central Macatuba - BOT"
  commitAuthorEmail: "centralmacatuba@gmail.com"
